### ISSUE TITLE
Request: Add named exports, separate exports from `package.json`

### ISSUE THREAD

**Issue by LufyCZ** [snapshot-labs/snapshot.js#1000]
As it stands, using any of the SDK's features [adds 200kB to the bundle](https://bundlephobia.com/package/@snapshot-labs/snapshot.js@0.11.23).

Would it be possible to:
A: Add named exports to the index.ts file
```
export { utils, ... }

export default {...}
```

and

B: Add separate node exports
```
"exports": {
    ".": {
      "types": "./dist/index.d.ts",
      "default": "./dist/index.js"
    },
    "./utils": {
      "types": "./dist/utils/index.d.ts",
      "default": "./dist/utils/index.js"
    },
},
```

Unfortunately, ATM, making use of even one feature creates a pretty big hit, allowing for a reduction in said hit would be great and greatly appreciated.

Thanks 😃

**Comment by ChaituVR** [comment]
Moved it to https://snapshot.canny.io/feature-requests/p/snapshotjs-add-named-exports-separate-exports for better visibility
