### ISSUE TITLE
Getting an error Cannot read properties of undefined (reading 'utils') while execution snapshot.utils.getVp() or any other method

### ISSUE THREAD

**Issue by HamzaBhatti125** [snapshot-labs/snapshot.js#1030]
### Expected behavior
According to the doc, the below mentioned method should return me some response.
snapshot.utils.getVp(address, network, strategies, snapshot, space, delegation, options).then(vp => {
  console.log('Voting Power', vp);
});
### Actual behavior
But I am getting an error TypeError: Cannot read properties of undefined (reading 'utils'). I have installed the package by using npm i @snapshot-labs/snapshot.js. I am using it in nestJs project
### Steps to reproduce the behavior
Just install the package and write the service code which is mentioned the snapshot.js doc

![image](https://github.com/snapshot-labs/snapshot.js/assets/40958101/1f8538c4-3aad-4278-a5af-2d9ecd734f65)
![image](https://github.com/snapshot-labs/snapshot.js/assets/40958101/bd269223-b299-4c96-bb1a-d27499cc7bf4)

**Comment by ChaituVR** [comment]
Hi @HamzaBhatti125 How do you import snapshot.js?

**Comment by HamzaBhatti125** [comment]
@ChaituVR I am importing in the same way as mentioned in the doc i.e.

import snapshot from '@snapshot-labs/snapshot.js';

I've also tried 
import {snapshot} from '@snapshot-labs/snapshot.js';
import {utils} from '@snapshot-labs/snapshot.js';

but it is giving me error while compiling
![image](https://github.com/snapshot-labs/snapshot.js/assets/40958101/024a717a-d4bd-4c57-9e27-64294dcf8aa6)

**Comment by ChaituVR** [comment]
Not an expert in nest.js but 

It works like this 

```ts
import * as snapshot from '@snapshot-labs/snapshot.js';

snapshot['utils'].getVp(....)
```

**Comment by ChaituVR** [comment]
Here is an example https://stackblitz.com/edit/nestjs-typescript-starter-elhxtv?file=src%2Fapp.service.ts

**Comment by HamzaBhatti125** [comment]
@ChaituVR It worked! thank you
