### ISSUE TITLE
Balancer strategy not working for smart pools

### ISSUE THREAD

**Issue by hammadj** [snapshot-labs/snapshot.js#115]
### Expected behavior
Snapshot should recognize users with LP tokens of a smart pool and count them towards the vote

### Actual behavior
Smart pool tokens aren't visible to the `balance` strategy, and users dont have any voting weight.

### Steps to reproduce the behavior

This is the JSON config I'm using for MetaFactory's snapshot config (https://snapshot.page/#/metafactory.eth/settings)

Link to the pool:  https://pools.balancer.exchange/#/pool/0x3c035c3f8e271e12df1bed648024e60249f507c3/

```json
{
  "symbol": "GEAR",
  "address": "0xfb5453340c03db5ade474b27e68b6a9c6b2823eb",
  "decimals": 18
}
```

Looking into the strategy, I can see that the Subgraph for Balancer doesn't list poolShares for the smart pools I have liquidity in: 
![image](https://user-images.githubusercontent.com/7143583/109567333-69029680-7aa2-11eb-9fc2-41afab630dc8.png)

Is there an updated subgraph that works with smart pools?

**Comment by sohkai** [comment]
Hey @hammadj, sorry it's taken this long to get back.

Unfortunately it looks like the Balancer team is focused primarily on their v2 launch and it's unlikely v1 smart pools will be included in the current subgraph in the near future. To add smart pools as a power source, it'd be easiest to submit a new strategy that does a multicall into the contract to get balances.
