### ISSUE TITLE
whitelist template doesn't allow add

### ISSUE THREAD

**Issue by futjrnaut** [snapshot-labs/snapshot.js#198]
### Expected behavior
copy paste whitelist strategy into add strategy whitelist
add button should show

### Actual behavior
add button unselectable
### Steps to reproduce the behavior
copy and paste the whitelist template into the white list strategy try to click add. 

hi 
i am trying to attach an array of addresses to whitelist for a tiered proposal system. 
Please advise.

**Comment by bonustrack** [comment]
@futjrnaut Did you find a solution? You most likely were missing the param "symbol" in your strategy params.
