### ISSUE TITLE
Checklist for adding a new strategy

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot.js#212]
Here is a simple checklist to look when reviewing a PR for a new strategy:

**Overview**
- The strategy must be unique.
- If the strategy does only a single call with an address as input, it's preferable to use the strategy "contract-call" instead of creating a new one.

**Code**
- There should be a maximum of 5 requests, a request can use "fetch" a "subgraphRequest" or "multicall".
- The strategy should not send a request for each voters, this doesn't scale.
- The strategy PR should not add any dependency in Snapshot.js.
- The score returned by the strategy should use the same casing for address than on the input, or should return checksummed addresses.

**Example**
- Example must include at least 1 address with a positive score.
- Example must use a snapshot block number in the past.

**Test**
- The strategy should take less than 10sec to resolve.
- The strategy should work with 500 addresses. [Here is a list of addresses](https://github.com/snapshot-labs/snapshot-strategies/blob/master/test/addresses.json).

**Recommended**
- Add a README.md file that describe the strategy and provide an example of parameters.
- Use string ABI instead of object.

**Comment by ChaituVR** [comment]
> Test
> - The strategy should take less than 10sec to resolve.
> - The strategy should work with 500 addresses. Here is a list of addresses.

@bonustrack less than 10 sec to resolve 500 address? or 1 address? is there any time limit for 500 addresses?

**Comment by bonustrack** [comment]
Less than 10sec for 500 addresses

**Comment by rude69** [comment]
qqq

**Comment by ChaituVR** [comment]
We now have these checks here https://github.com/snapshot-labs/snapshot-strategies#code
