### ISSUE TITLE
Spaces are limited to five strategies

### ISSUE THREAD

**Issue by ncitron** [snapshot-labs/snapshot.js#229]
### Expected behavior
Spaces should be allowed to add more than five snapshot strategies.

### Actual behavior
Five strategies are the limit, as defined in src/schemas/space.json

### Steps to reproduce the behavior
Attempt to add greater than five strategies to a snapshot space

### Notes
The Index Coop is planning to add additional strategies to our space to better represent our token holders. At the moment, we use four strategies but intend to add an additional three strategies once we migrate to ENS. I have considered writing a custom strategy that wraps multiple strategies together, but it would be significantly simpler if we could bump the maximum allowed strategies from 5 to 10 to accommodate our needs.

**Comment by bonustrack** [comment]
@ncitron Which strategies do you want to use? Having 10 strategies can be problematic because these strategies are sending many requests and these requests are executed on the user browser, it would become too heavy or slow or to heavy to process.

**Comment by ncitron** [comment]
Thank you for providing some context here. I guess we will have to prioritize our most important strategies.
