### ISSUE TITLE
BSC chain failing to connect

### ISSUE THREAD

**Issue by Janther** [snapshot-labs/snapshot.js#237]
### Expected behavior

Queries to the  BSC should not fail connection.

### Actual behavior

The console log for the browser shows this

<img width="990" alt="Screen Shot 2021-05-28 at 5 39 14 PM" src="https://user-images.githubusercontent.com/1022054/119935461-a2806a80-bfdb-11eb-9d3b-324690b0738d.png">

This error appeared when trying to `getScores()` in my local machine, and on production with our space based on this chain.
I believe the API KEY might be outdated. Since I generated a new for myself and everything worked out.

### Steps to reproduce the behavior

Try any query to this Chain.

**Comment by bonustrack** [comment]
Closing this issue, this been fixed already. If you're still having issues please open another issue.
