### ISSUE TITLE
Vote by API

### ISSUE THREAD

**Issue by 0xtsukino** [snapshot-labs/snapshot.js#341]
Hello 👋  - I am trying to see if it's possible to integrate with Snapshot voting thru API. I looked through the docs and seems like its possible since there is a Gnosis app, but couldn't find any more relevant detail. Could someone point me to the right direction?

**Comment by bonustrack** [comment]
@0xtsukino This part is not documented yet. You will need to use Snapshot.js Client, this one: https://github.com/snapshot-labs/snapshot.js/blob/master/src/client.ts , This is how you can init the client: https://github.com/snapshot-labs/snapshot/blob/develop/src/helpers/client.ts
Then you can use the function "vote" with a Ethers.js Web3Provider <https://github.com/snapshot-labs/snapshot.js/blob/master/src/client.ts#L66-L77> to sign and broadcast a proposal. Let me know if you have question i can help

**Comment by mykcryptodev** [comment]
@0xtsukino is there a timeline for the "Vote by API" documentation to be published?

**Comment by ChaituVR** [comment]
https://docs.snapshot.org/snapshot.js#cast-a-vote
