### ISSUE TITLE
score.snapshot.org CORS policy blocking API queries.

### ISSUE THREAD

**Issue by jnaviask** [snapshot-labs/snapshot.js#350]
### Expected behavior

We make a call to `snapshot.utils.getScores` and fetch a user's score.

### Actual behavior

Call to `snapshot.utils.getScores` prints the following in console:

```
Access to XMLHttpRequest at 'https://score.snapshot.org/api/scores' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

### Steps to reproduce the behavior

Will be present on any site outside of the `snapshot.org` domain utilizing the snapshot API to query `getScores`.

**Comment by bonustrack** [comment]
@jnaviask Can you provide some example of parameters for the getScores function that give you this error?

**Comment by jnaviask** [comment]
After fetching space via graphql (all parameters have the same name as in graphql), the following:

```
snapshot.utils.getScores(
  space.id,
  space.strategies,
  space.network,
  snapshot.utils.getProvider(space.network),
  ["0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"],
)
```

**Comment by jnaviask** [comment]
I was testing against https://snapshot.org/#/ybaby.eth, but it seems to be returning correctly now for some reason, so I'm going to close this ticket.
