### ISSUE TITLE
Strategy symbol error

### ISSUE THREAD

**Issue by maswalker** [snapshot-labs/snapshot.js#377]
### Expected behavior
Symbol should be 'IOTX'

### Actual behavior
Symbol is 'DAI'

### Steps to reproduce the behavio
click strategy information button as below

![11](https://user-images.githubusercontent.com/75085457/133707236-51ad53fb-84b8-41ad-bd6b-1ce9592fd0d2.jpg)
<img width="1257" alt="13" src="https://user-images.githubusercontent.com/75085457/133708924-c26342c2-90a9-48c2-bfe6-ea55d874221f.png">

**Comment by ChaituVR** [comment]
@maswalker This one is from your space settings:

It is like this now:
```
"params": {
"symbol": "DAI",
"address": "0x6B175474E89094C44Da98b954EedeAC495271d0F",
"decimals": 18
}
```
please change the `symbol` param as per your requirement,
Closing this issue for now, please feel free to reopen this if required
