### ISSUE TITLE
Custom Network Support

### ISSUE THREAD

**Issue by CjHare** [snapshot-labs/snapshot.js#381]
A new Snapshot user here, it looks like a great product 👍 

The use case have for Snapshot is developing (& testing) a custom strategy against an in-memory network. When the strategy is eventually live, the CI testing will remain as part of the CI/CD pipeline (so it'll be a feature needed beyond the initial strategy development).

Although running Snapshot against a network defined outside of the `networks.json` is not is not currently a feature, if it is a feature you'd like, I'll happily port the changes from my open PR https://github.com/snapshot-labs/snapshot-strategies/pull/79

Generally speaking, this change switches the sourcing of the `networks json` from being hard-coded import to a CLI option, with the default being the `network.json`

The use case(s) supported by such a change are:
- Running strategy tests on CI boxes 
- Running Snapshot against private networks

Let me. know if this is a change you'd like me to create a PR on, or if there's a better solution in this case with Snapshot 🙂 

### Desired behavior
Run Snapshot against a network whose definition is in a custom json file.

### Actual behavior
The neworks.json from Snapshot.js is used.

### Steps to reproduce the behavior
Running a test on the default strategy, with the network being a local Ethereum node.

**Comment by ChaituVR** [comment]
Now it is very easy to add a network :) https://docs.snapshot.org/developer-guides/networks
