### ISSUE TITLE
Support custom score API URL for testing

### ISSUE THREAD

**Issue by mktcode** [snapshot-labs/snapshot.js#402]
Analogous to: https://github.com/snapshot-labs/snapshot/pull/918
We could replace: https://github.com/snapshot-labs/snapshot.js/blob/81f100e032a557a6a5bd1ae4fc6488911fb48e88/src/utils.ts#L22
...with an optional last parameter here: https://github.com/snapshot-labs/snapshot.js/blob/81f100e032a557a6a5bd1ae4fc6488911fb48e88/src/utils.ts#L115-L122
...defaulting to `https://score.snapshot.org` if not set of course.

**Comment by bonustrack** [comment]
Also the "provider" param is not necessary anymore, we can remove it and add the score api url as last param
