### ISSUE TITLE
GraphQL: Cannot get score when proposal is open

### ISSUE THREAD

**Issue by odcey** [snapshot-labs/snapshot.js#452]
### Expected behavior
Retrieve proposal score from graphQL query

### Actual behavior
Not retrieving score from graphQL query

### Steps to reproduce the behavior
```gql
query Proposal {
  proposal(id: "0xb7356adb5ee9f59aeaa97b6af2d69ac0d6d4628f8a40303c433d1474e0064914") {
    id
    votes
    snapshot
    scores
    scores_state
    scores_updated
    scores_by_strategy
  }
}
```

returns 
```json
{
  "data": {
    "proposal": {
      "id": "0xb7356adb5ee9f59aeaa97b6af2d69ac0d6d4628f8a40303c433d1474e0064914",
      "votes": 0,
      "snapshot": "13791875",
      "scores": [],
      "scores_state": "",
      "scores_updated": 0,
      "scores_by_strategy": []
    }
  }
}
```
But the website is showing 
<img width="362" alt="snapshot" src="https://user-images.githubusercontent.com/8565879/145732219-46159c23-9a90-4bba-90ef-03d79f26906a.png">

I also tried to get voters addresses from graphql query
then call getScore method
which is returning 262.86 and not 720.16

I'm trying to get the 720.16 from code, how do i do that ? 

Thanks a lot !

**Comment by samuveth** [comment]
Currently you can only get the score from our graphql api if the proposal is closed. If you need to get scores from an open proposals you can use `getScores` in snapshot.js

**Comment by odcey** [comment]
Hi, thank you for your response.
It looks like its now possible to query score of opened/active proposal
for example
```gql
query  {
  proposal (id: "0xb7356adb5ee9f59aeaa97b6af2d69ac0d6d4628f8a40303c433d1474e0064914") {
    id
    votes
    scores
  }
}
```

Did you changed this recently ? Wasn't possible yesterday. 
If you made changes this is great !!
Can you confirm i can use this method to get current choices scores of open proposal please ?

**Comment by ChaituVR** [comment]
@odcey Even though scores are returned for open/active proposals - they may not be correct scores, better to use getScores from snapshot.js
For closed proposals we can relay on this :)

But yea we are looking for ways to have scores for open/active proposals too (right now there are few blockers)

**Comment by odcey** [comment]
@ChaituVR I think i found a way making 3 request
Step1: Get voters of proposal id
Step2: Get proposal strategies + snapshot
Step3: getScores

I had issue because getScores return is really strange, sometimes putting scores on wrong proposal choices
But i mapped with step1 voters choice and seems ok
And making the sum of all voters for a choice

Would be awesome if you find a way to easily get current score for a choice of active proposal
To avoid all the steps above

Thank you and good luck !
