### ISSUE TITLE
utils.getScores() not working 

### ISSUE THREAD

**Issue by Lorenzobattistela** [snapshot-labs/snapshot.js#652]
### Expected behavior
Return a list, a sum of scores of all addresses of voters specified in parameters, as described in the documentation here: https://docs.snapshot.org/snapshot.js#getscores

### Actual behavior
Returns `TypeError: Cannot read properties of undefined (reading 'scores')`

I investigated a little bit and found out that the problem is in [this line](https://github.com/snapshot-labs/snapshot.js/blob/master/src/utils.ts#L179). Something is going wrong when reading the object returned by the API.

### Steps to reproduce the behavior

I copied the code presented in the documentation in [this link](https://docs.snapshot.org/snapshot.js#getscores). The code was exactly the same.

**Comment by ChaituVR** [comment]
Hi @Lorenzobattistela This happens when there is some error or problem with the strategies passed, you can check if these strategies are working or not from the strategy playground
