### ISSUE TITLE
added custom domain for phinetwork.eth to phi.vote

### ISSUE THREAD

**Issue by Phinetwork** [snapshot-labs/snapshot.js#699]
added custom domain for phinetwork.eth to phi.vote

#### Hi! What is your PR about?

- [ ] Add or edit a skin
- [x] Add a custom domain for your space
- [ ] Add an alias to migrate your space

__Originally posted by @Phinetwork in https://github.com/snapshot-labs/snapshot-spaces/pull/2197__

**Comment by ChaituVR** [comment]
What is the need for this issue?

**Comment by Phinetwork** [comment]
> What is the need for this issue?

This is already merged it wasn't at the time of this issue request thanks it's all set
