### ISSUE TITLE
Enforce checksum address on sign

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot.js#712]
- I think you can just do it here https://github.com/snapshot-labs/snapshot.js/blob/master/src/sign/index.ts#L55
- using https://docs.ethers.io/v5/api/utils/address/#utils-getAddress from https://www.npmjs.com/package/@ethersproject/address
- We have to check all methods in this class (vote/proposal/settings etc. ) should make sure they work fine even if we pass an address in any case
- To run these methods you can follow https://docs.snapshot.org/snapshot.js

**Comment by emanuel-sol** [comment]
Working on this now.

**Comment by emanuel-sol** [comment]
A PR for this issue has been merged to develop #743

**Comment by emanuel-sol** [comment]
@bonustrack just wanted to confirm with you that this bounty has been completed, right?
