### ISSUE TITLE
Add Hedera network

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot.js#718]
Here is some public node:
https://swirldslabs.com/hashio/

**Comment by ChaituVR** [comment]
Chain id 295
explorer: https://hashscan.io/#/mainnet/accounts

I don't think this chain is EVM https://docs.hedera.com/guides/core-concepts/smart-contracts/hyperledger-besu-evm Addreses, contracts and blocks are in different format

**Comment by bonustrack** [comment]
Did you tried this node https://mainnet.hashio.io/api ?

**Comment by ChaituVR** [comment]
Yep, it works and I get chainID from it, problem is that their addresses, contracts, and blocks are in different formats

**Comment by ChaituVR** [comment]
{
  "key": "296",
  "name": "Hedera Testnet",
  "shortName": "Hedera Testnet",
  "chainId": 296,
  "network": "Hedera Testnet",
  "testnet": true,
  "multicall": "0x0000000000000000000000000000000002e5a188",
  "rpc": [
    "https://testnet.hashio.io/api"
  ],
  "explorer": "https://hashscan.io/#/testnet/",
  "start": 48603528,
  "logo": "ipfs://bafkreicizgwcwo5sffhjwmc5ifn3lrl2lr47qupxsfnvvqtqwfos6y27gu"
}

Need to check:
- [ ] start block
- [ ] Check payload limit (works only with one address)
- [ ] Check multicall with other addresses and blocks

**Comment by ChaituVR** [comment]
Mainnet:

```json
"295": {
  "key": "295",
  "name": "Hedera Mainnet",
  "shortName": "Hedera",
  "chainId": 295,
  "network": "Hedera",
  "multicall": "0x000000000000000000000000000000000014bbfb",
  "rpc": [
    "http://44.192.14.188:7546"
  ],
  "explorer": "https://hashscan.io/#/mainnet/",
  "start": 39113460,
  "logo": "ipfs://bafkreicizgwcwo5sffhjwmc5ifn3lrl2lr47qupxsfnvvqtqwfos6y27gu"
}
```

**Comment by zzuziak** [comment]
Hey @ChaituVR what's the status on this issue? 🙏

**Comment by bonustrack** [comment]
@zzuziak There is still some blockers to integrate Hedera, we have a chat on Telegram with some partner will add you.

**Comment by ChaituVR** [comment]
The main problem is their RPC nodes are not EVM equivalent (though their network is EVM compatible)

**Comment by zzuziak** [comment]
Shall we move it to backlog for now then?

**Comment by ChaituVR** [comment]
Yep, i think we should.

**Comment by ChaituVR** [comment]
Closing this for now
