### ISSUE TITLE
Clear cache is running infinitely in snapshot-strategies

### ISSUE THREAD

**Issue by payvint** [snapshot-labs/snapshot.js#856]
In snapshot-strategies repo
After changes provided in this PR https://github.com/snapshot-labs/snapshot.js/pull/851
All the tests are running infinitely(till the test timeout)
You can check a PR to snapshot-strategies repo here:
https://github.com/snapshot-labs/snapshot-strategies/pull/1193

I want to run test for strategy erc20-balance-off via command `yarn test --strategy=erc20-balance-of --more=500 --detectOpenHandles`

In snapshot.js version 0.4.97 - all tests are running fine
In version 0.4.98 and above - running with current issue

### Expected behavior
Will finish and show nothing

### Actual behavior
Did not finish and show
![Screenshot 2023-06-20 at 22 06 28](https://github.com/snapshot-labs/snapshot.js/assets/15244661/35eb41a6-6c6b-4f2d-afbd-5d8dafa764b4)

### Steps to reproduce the behavior
Download snapshot-strategies repo
run `yarn install`
run `yarn test --strategy=erc20-balance-of --more=500 --detectOpenHandles`

**Comment by ChaituVR** [comment]
Fixed in https://github.com/snapshot-labs/snapshot-strategies/commit/023a25db310452fd8d9e73e3d22efabe5e888b1f and https://github.com/snapshot-labs/snapshot-strategies/commit/ca4e43bde2c0edbc0e5a2a6a8f4aa86da7c0efb7
