### ISSUE TITLE
this https://rpc.snapshot.org/813 is error

### ISSUE THREAD

**Issue by cleerbit** [snapshot-labs/snapshot.js#896]
### Expected behavior
create new proposal

### Actual behavior
error: We encountered an error while fetching the snapshot block number which is needed to calculate your voting power. Please try again later.

### Steps to reproduce the behavior
check network
https://rpc.snapshot.org/813 is bad

**Comment by ChaituVR** [comment]
Hi @cleerbit Can share your Space?

I see their RPC node URL is changed, updated it, You should not face this issue now, Let me know
