### ISSUE TITLE
Cannot vote on proposals using Shutter shielding via Snapshot API

### ISSUE THREAD

**Issue by SheeranJL** [snapshot-labs/snapshot.js#954]
Hello,

Having issues using the API to vote on proposals that are using Shutter. I could not find any documentation around this and whether there's something else I should be doing for these proposals that might be different to others not using Shutter. Any advice is appreciated, including pointing me to any documentation i may have missed. Cheers

### Expected behavior

To be able to vote on proposals implemented with Shutter shielding the same way as we are able to vote on any other proposals, using the endpoint as provided in the Snapshot documentation, specifically the 'Cast a vote' section.

### Actual behavior

Error when trying to do so,

**Error 1**: was '**reason not allowed with shutter**' which was overcome by removing that from the .vote()
**Error 2** now failing with **invalid choice** (the choice is an integer representing the vote)

### Steps to reproduce the behavior

Here is the code, this works for all other proposals that aren't using Shutter. I suppose there's another method I should be calling instead given the nature of what it does. 

`   
const receipt = await client.vote(wallet, account, {space,  proposal, type,  choice, metadata: JSON.stringify({app:proposal.space.name})});
`

**Comment by ChaituVR** [comment]
Hey @SheeranJL Yes you may need extra setup on your frontend to vote with shutter, right now it is not documented, so you may have to reverse-engineer our front end to encrpyt the votes

**Comment by SheeranJL** [comment]
@ChaituVR Thanks for the quick reply mate, I thought as such. Much appreciated.

**Comment by ChaituVR** [comment]
Refer to https://github.com/snapshot-labs/snapshot/blob/master/src/helpers/shutter.ts#L8 to encrpyt choice before passing it to `vote`

**Comment by SheeranJL** [comment]
I managed to get the opportunity to test voting directly on the Snapshot UI for a proposal where I have delegation rights.

When I vote using the Snapshot interface, everything works as expected. However, I still encounter issues when attempting to replicate this process in code. The core problem persists as noted earlier, the choice parameter is expected to be a uint32 type, but the encrypted hex string  significantly exceeds the 32 bits of data.

It works when I vote on Snapshot UI, but still not in code. The same problem persists where Choice is expecting a uint32 type but of course the encrypted hex string exceeds 32 bits of data 

Could there be a specific handling or conversion in the Snapshot UI to account for this?

**Comment by SheeranJL** [comment]
Resolved by including `privacy: 'shutter'` as an argument passed to vote()
