### ISSUE TITLE
Failure on client.follow() and client.unfollow()

### ISSUE THREAD

**Issue by vswee** [snapshot-labs/snapshot.js#990]
### Expected behaviour
Join or Leave a space by calling function

### Actual behavior
Throws error:
```TypeError: can't access property "length", str is undefined```

### Steps to reproduce the behavior
Call async function `await client.follow(web3, account, {  "name":space})` or `await client.unfollow(web3, account, {  "name":space})`

**Comment by ChaituVR** [comment]
Hi @vswee Follow and unfollow expect a alias wallet to sign the message, refer to https://github.com/snapshot-labs/snapshot/blob/master/src/composables/useFollowSpace.ts#L63-L100
